### ISSUE TITLE
Navbuilder blockt Update auf yForm 4.0.0

### ISSUE THREAD

**Issue by iceman-fx** [FriendsOfREDAXO/navbuilder#13]
AddOn yform konnte aus folgendem Grund nicht aktualisiert werden:
AddOn navbuilder meldet: Das AddOn yform (Version 4.0.0) entspricht nicht der geforderten Versionsbedingung ^3.3.1!

**Comment by iceman-fx** [comment]
Kann ich auch bestätigen.
Dieser Fix funktioniert einwandfrei.

Bitte freigegen und im Installer aktualisieren.

**Comment by alxndr-w** [comment]
#12
