### ISSUE TITLE
Anpassungen

### ISSUE THREAD

**Issue by AndiLeni** [FriendsOfREDAXO/navbuilder#6]
Hallo,

ich möchte gerne dieses Addon nutzen, um eine Navigation für Bootstrap zu bauen.
Gibt es eine Mäglichkeit, die class-Attribute über das Backend anzupassen, oder muss ich das Addon forken und mir selbst zurechtzimmern bis es passt?

Gruß
Andi

**Comment by thielpeter** [comment]
@AndiLeni Vielleicht hilft dir ja die neue Funktion getStructure()? Siehe https://github.com/FriendsOfREDAXO/navbuilder/pull/10

**Comment by erraiva** [comment]
Hallo, gibt es ein Anwedungsbeispiel für getStructure() für die Nichtsoschlauen? Ich würde gerne probieren, ob ich eine Bootstrapnavi damit hinbekomme. Grüße v. Heinz

**Comment by thielpeter** [comment]
Hallo @erraiva,

ein Beispiel könnte für https://getbootstrap.com/docs/4.0/components/navbar/ so aussehen: 
[navbuilder_getstructure_example.txt](https://github.com/FriendsOfREDAXO/navbuilder/files/4464814/navbuilder_getstructure_example.txt)

Schöne Ostern :)
Peter

**Comment by erraiva** [comment]
Hallo Peter,
ich komme leider erst jetzt dazu, den Navbuilder für ein Projekt auszuprobieren.
Dein Code ist eine Super-Vorlage, ich werde damit die Navigation machen.
Danke und Grüße
Heinz

**Comment by thielpeter** [comment]
@erraiva freut mich, dass ich dir helfen konnte :)
