### ISSUE TITLE
Problem bei zwei oder mehr Instanzen auf derselben Seite

### ISSUE THREAD

**Issue by netzproductions** [FriendsOfREDAXO/navbuilder#8]
Wenn der Navbuilder zweimal per Shortcode eingebaut wird (egal ob 2x die gleiche Nav oder zwei verschiedene), greift der RegEx im OUTPUT_FILTER nicht mehr korrekt, da hier nicht non-greedy gesucht wird.
Lösung:
`preg_match_all("/REX_NAVBUILDER\[name=(.*?)]/", $content, $matches, PREG_SET_ORDER);`
statt
`preg_match_all("/REX_NAVBUILDER\[name=(.*)]/", $content, $matches, PREG_SET_ORDER);`

**Comment by thielpeter** [comment]
Vielen Dank für den Hinweis, wurde gefixt.
